AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'test/**/test_*.rb'

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
